--    ['4runner'] = {
--        ['name'] = '2020 Toyota 4Runner',
--        ['brand'] = 'Toyota',
--        ['model'] = '4runner',
--        ['price'] = 39000,
--        ['category'] = 'suvs',
--        ['hash'] = `4runner`,
--        ['shop'] = 'pdm',
--    },
--    ['tltypes'] = {
--        ['name'] = 'TL Type-S,
--        ['brand'] = 'Acura',
--        ['model'] = 'tltypes',
--        ['price'] = 20000,
--        ['category'] = 'sedans',
--        ['hash'] = `tltypes`,
--        ['shop'] = 'pdm',
--    },
--    ['amdbx'] = {
--        ['name'] = 'DBX Carbon Edition',
--        ['brand'] = 'Aston Martin',
--        ['model'] = 'amdbx',
--        ['price'] = 120000,
--        ['category'] = 'suvs',
--        ['hash'] = `amdbx`,
--        ['shop'] = 'luxury',
--    },
    ['ast'] = {
        ['name'] = '2013 Vanquish',
        ['brand'] = 'Aston Martin',
        ['model'] = 'ast',
        ['price'] = 130000,
        ['category'] = 'sports',
        ['hash'] = 'ast',
        ['shop'] = 'luxury',
    },
    ['80b4'] = {
        ['name'] = '1995 Cabriolett',
        ['brand'] = 'Audi',
        ['model'] = '80b4',
        ['price'] = 25000,
        ['category'] = 'sports',
        ['hash'] = '80b4',
        ['shop'] = 'pdm',
    },
    ['aaq4'] = {
        ['name'] = '2017 A4 Quattro ABT',
        ['brand'] = 'Audi',
        ['model'] = 'aaq4',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'aaq4',
        ['shop'] = 'pdm',
    },
    ['audquattros'] = {
        ['name'] = '1983 Quattro Sport',
        ['brand'] = 'Audi',
        ['model'] = 'audquattros',
        ['price'] = 20000,
        ['category'] = 'sports',
        ['hash'] = 'audquattros',
        ['shop'] = 'pdm',
    },
    ['q820'] = {
        ['name'] = '2020 Q8 50TDI',
        ['brand'] = 'Audi',
        ['model'] = 'q820',
        ['price'] = 45000,
        ['category'] = 'sports',
        ['hash'] = 'q820',
        ['shop'] = 'pdm',
    },
    ['r8ppi'] = {
        ['name'] = '2013 R8 V10',
        ['brand'] = 'Audi',
        ['model'] = 'r8ppi',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'r8ppi',
        ['shop'] = 'pdm',
    },
    ['r820'] = {
        ['name'] = '2020 R8',
        ['brand'] = 'Audi',
        ['model'] = 'r820',
        ['price'] = 50000,
        ['category'] = 'sports',
        ['hash'] = 'r820',
        ['shop'] = 'pdm',
    },
    ['rs6'] = {
        ['name'] = '2016 RS6 C7 Performance',
        ['brand'] = 'Audi',
        ['model'] = 'rs6',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'rs6',
        ['shop'] = 'pdm',
    },
    ['rs72020'] = {
        ['name'] = '2020 RS7',
        ['brand'] = 'Audi',
        ['model'] = 'rs72020',
        ['price'] = 45000,
        ['category'] = 'sports',
        ['hash'] = 'rs72020',
        ['shop'] = 'pdm',
    },
    ['s8d2'] = {
        ['name'] = '1998 S8 (D2/PFL)',
        ['brand'] = 'Audi',
        ['model'] = 's8d2',
        ['price'] = 25000,
        ['category'] = 'sports',
        ['hash'] = 's8d2',
        ['shop'] = 'pdm',
    },
    ['sq72016'] = {
        ['name'] = '2016 SQ7',
        ['brand'] = 'Audi',
        ['model'] = 'sq72016',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'sq72016',
        ['shop'] = 'pdm',
    },
    ['ttrs'] = {
        ['name'] = '2010 TT RS',
        ['brand'] = 'Audi',
        ['model'] = 'ttrs',
        ['price'] = 30000,
        ['category'] = 'sports',
        ['hash'] = 'ttrs',
        ['shop'] = 'pdm',
    },
    ['bbentayga'] = {
        ['name'] = 'Bentayga',
        ['brand'] = 'Bentley',
        ['model'] = 'bbentayga',
        ['price'] = 500000,
        ['category'] = 'sedans',
        ['hash'] = 'bbentayga',
        ['shop'] = 'luxury',
    },
    ['cgts'] = {
        ['name'] = '2020 Continental GT Convertible',
        ['brand'] = 'Bentley',
        ['model'] = 'cgts',
        ['price'] = 600000,
        ['category'] = 'sedans',
        ['hash'] = 'cgts',
        ['shop'] = 'luxury',
    },
    ['760li04'] = {
        ['name'] = '2004 760Li Individual (E66/PFL)',
        ['brand'] = 'BMW',
        ['model'] = '760li04',
        ['price'] = 45000,
        ['category'] = 'sports',
        ['hash'] = '760li04',
        ['shop'] = 'pdm',
    },
    ['e34'] = {
        ['name'] = '1995 M5 E34',
        ['brand'] = 'BMW',
        ['model'] = 'e34',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'e34',
        ['shop'] = 'pdm',
    },
    ['m2'] = {
        ['name'] = '2016 M2',
        ['brand'] = 'BMW',
        ['model'] = 'm2',
        ['price'] = 40000,
        ['category'] = 'sports',
        ['hash'] = 'm2',
        ['shop'] = 'pdm',
    },
    ['m3e36'] = {
        ['name'] = '1997 M3 E36',
        ['brand'] = 'BMW',
        ['model'] = 'm3e36',
        ['price'] = 30000,
        ['category'] = 'sports',
        ['hash'] = 'm3e36',
        ['shop'] = 'pdm',
    },
    ['m3e92'] = {
        ['name'] = '2008 M3 e92',
        ['brand'] = 'BMW',
        ['model'] = 'm3e92',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['hash'] = 'm3e92',
        ['shop'] = 'pdm',
    },
    ['bmci'] = {
        ['name'] = '2018 M5 F90',
        ['brand'] = 'BMW',
        ['model'] = 'bmci',
        ['price'] = 48000,
        ['category'] = 'sports',
        ['hash'] = 'bmci',
        ['shop'] = 'pdm',
    },
    ['x6m'] = {
        ['name'] = 'X6M F16',
        ['brand'] = 'BMW',
        ['model'] = 'x6m',
        ['price'] = 26000,
        ['category'] = 'sports',
        ['hash'] = 'x6m',
        ['shop'] = 'pdm',
    },
    ['x5e53'] = {
        ['name'] = '2005 X5 E53 Sport Package',
        ['brand'] = 'BMW',
        ['model'] = 'x5e53',
        ['price'] = 36000,
        ['category'] = 'sports',
        ['hash'] = 'x5e53',
        ['shop'] = 'pdm',
    },
